### ISSUE TITLE
Agenda: Governance, May 7 2019

### ISSUE THREAD

**Issue by lehnberg** [mimblewimble/grin-pm#115]
Solicit suggestions for agenda items for the Governance meeting to be held on Tuesday May 7 @ 15:00 [UTC](http://www.timebie.com/std/utc.php) in [Gitter main lobby](
https://gitter.im/grin_community/Lobby). Please comment to provide topics or suggestions.

# Proposed agenda
1. Agenda review
1. Action point follow ups from previous meeting
   * [X] @lehnberg [issue for friends of grin improvement created](https://github.com/mimblewimble/site/issues/126) on `/site`. 
1. [Security audit status](https://github.com/mimblewimble/grin/issues/1609) & security vulnerability process review
1. Funding status
   1. [Transparency report status](https://github.com/mimblewimble/grin-pm/blob/master/financials/reports/funding_transparency_2019Q1.md)
   1. [Budget status](https://github.com/mimblewimble/grin-pm/issues/130)
1. Simplify grin onboarding process
   something like bitcoin.org or z.cash):
   * Add binaries.
   * Link to GUI wallets.
   * Avoid going on GitHub when possible.
1. Promotion of other projects
1. Grin evangelism
1. Other questions

**Comment by quentinlesceller** [comment]
I'd like to discuss a change on the website to simplify the on boarding process: 
- Add binaries.
- Link to GUI wallets.
- Avoid going on GitHub if possible.
