### ISSUE TITLE
Agenda: Governance May 21 2019

### ISSUE THREAD

**Issue by lehnberg** [mimblewimble/grin-pm#134]
Solicit suggestions for agenda items for the Governance meeting to be held on Tuesday May 21 @ 15:00 [UTC](http://www.timebie.com/std/utc.php) in [Gitter main lobby](
https://gitter.im/grin_community/Lobby). Please comment to provide topics or suggestions.

# Proposed agenda
1. Agenda review
1. Action point follow ups from previous meeting
   * Status of misc. `/site` improvements
      * [ ] Budget display
      * [ ] Friends of grin
      * [ ] Binaries download/onboarding flow 
1. [Security audit status](https://github.com/mimblewimble/grin/issues/1609) & security vulnerability process review
1. Funding status
   1. [Budget status](https://github.com/mimblewimble/grin-pm/issues/130)
1. Promotion of other projects
1. Grin evangelism
1. Other questions

**Comment by chisa0a** [comment]
At the request of @mcdallas, would like to add [grin/docs](https://github.com/mimblewimble/docs) + Wiki access control to the agenda.
