### ISSUE TITLE
Support Grin donations in ETH

### ISSUE THREAD

**Issue by lehnberg** [mimblewimble/grin-pm#14]
As discussed in the [Nov 6 Governance meeting](
https://gitter.im/grin_community/Lobby?at=5be1b1c8cdc12d25bb804e50), it is be desired to set up donations to Grin to an ETH mu-sig wallet.

**Comment by kargakis** [comment]
Fixed by https://github.com/mimblewimble/site/commit/a392813365397e1df8be74ace4cdb1800de6bc62
