### ISSUE TITLE
Agenda: Governance Jun 04 2019

### ISSUE THREAD

**Issue by lehnberg** [mimblewimble/grin-pm#141]
Solicit suggestions for agenda items for the Governance meeting to be held on Tuesday June 04 @ 15:00 [UTC](http://www.timebie.com/std/utc.php) in [Gitter main lobby](
https://gitter.im/grin_community/Lobby). Please comment to provide topics or suggestions.

# Proposed agenda
1. Agenda review
1. Action point follow ups from previous meeting
   * Status of misc. `/site` improvements
      * [ ] Budget display
      * [ ] Friends of grin
      * [ ] Binaries download/onboarding flow 
1. [Security audit status](https://github.com/mimblewimble/grin/issues/1609) & security vulnerability process review
1. Funding status
   1. [Budget status](https://github.com/mimblewimble/grin-pm/issues/130)
1. [Tentative hard fork timeline](https://docs.google.com/document/d/1ef7L0374gdjY9Eux4Jjr551y1EF5DEdlN2RjLq1fYP8/edit?usp=sharing)
1. Bug bounties
1. Promotion of other projects
1. Grin evangelism
1. Governance working group
1. Slogan change to "no more funny money"
1. Other questions

**Comment by quentinlesceller** [comment]
Additional topic: tentative hard fork timeline -> https://docs.google.com/document/d/1ef7L0374gdjY9Eux4Jjr551y1EF5DEdlN2RjLq1fYP8/edit?usp=sharing.

**Comment by 0xb100d** [comment]
Just want to pop idea of a slogan change from the unofficial “better money” ( since it is/was a Chaum trademark) to “no more funny money” or some other alternative.

**Comment by lehnberg** [comment]
Updated agenda - included a governance working group item in addition
