### ISSUE TITLE
Agenda: Development, June 11 2019

### ISSUE THREAD

**Issue by bladedoyle** [mimblewimble/grin-pm#143]
Solicit suggestions for agenda items for the Development meeting to be held on Tuesday June 11 @ 15:00 [UTC](http://www.timebie.com/std/utc.php) in [Grin/Dev Gitter](
https://gitter.im/grin_community/dev). Please comment to provide topics or suggestions. 

# Proposed agenda
1. Igno's Retrospective
1. Agenda review
1. Action point follow ups from previous meetings
   * [ ] @lehnberg v1.1.0 communication?
   * [ ] @ignopeverell documentation of git branching model (linked to in CONTRIBUTING)?
   * [ ] @quentinlesceller secp256k1-zkp on azure-pipelines?
   * [ ] @hashmap integration tests review?
   * [ ] @yeastplume security audit report findings issues filed?
1. Security review status
1. Grin `v1.1.0`
1. Grin `v2.0.0`
1. Review our branching model
1. POW: Putting phaseouts on hold
1. Other questions

**Comment by lehnberg** [comment]
@bladedoyle perhaps join tomorrow’s extra meeting (3PM UTC, same time as usual) in order to join in on the discussion?

**Comment by bladedoyle** [comment]
Yes, thank you @lehnberg.

**Comment by lehnberg** [comment]
Agenda updated.

**Comment by garyyu** [comment]
I strongly propose we define a dev branch, to be discussed in dev meeting:

https://gitter.im/grin_community/dev?at=5cf921e4bf4cbd167c3e7a01

How about define `master` as dev branch? to merge any reviewed PRs into `master` (i.e. dev branch).

- For example, if we need `1.1.1` release, we can branch from tag `1.1.0` for it;
- and after `1.1.1` release, if we still feel `1.1.2` release is needed, we can branch from tag `1.1.1` for it,
- and so on.

> I think we need to start shifting expectations slightly around how long it should take for a PR or new concept to go from initial introduction into fully merged and targeting a particular release.
but can’t be too long, for the inspiring the developers.

We can make it longer before it go into a release, but i think we should NOT make it longer to merge/accept it (to dev branch for example).

**Comment by quentinlesceller** [comment]
@tromp wanted to discuss [Grin Improvement Proposal 1: put later phase outs on hold and rephrase primary PoW commitment](https://www.grin-forum.org/t/grin-improvement-proposal-1-put-later-phase-outs-on-hold-and-rephrase-primary-pow-commitment/4653/36).

**Comment by lehnberg** [comment]
@quentinlesceller it's actually for [next week's meeting](https://github.com/mimblewimble/grin-pm/issues/147#issuecomment-500233083), but it wouldn't hurt raising today either.

Agenda updated.

**Comment by quentinlesceller** [comment]
@lehnberg oups my bad :)

**Comment by tromp** [comment]
I thought that was a governance decision...
