### ISSUE TITLE
Agenda: Governance Jun 18 2019

### ISSUE THREAD

**Issue by lehnberg** [mimblewimble/grin-pm#147]
Solicit suggestions for agenda items for the Governance meeting to be held on Tuesday June 04 @ 15:00 [UTC](http://www.timebie.com/std/utc.php) in [Gitter main lobby](
https://gitter.im/grin_community/Lobby). Please comment to provide topics or suggestions.

# Proposed agenda
1. Agenda review
1. Action point follow ups from previous meeting
   * Status of misc. `/site` improvements
      * [ ] Budget display
      * [ ] Friends of grin
      * [ ] Binaries download/onboarding flow 
   * [X] @hashmap @lehnberg comms channel for pools & exchanges
   * [X] @quentinlesceller hard fork document published
1. POW: [Putting Phaseouts on hold](https://www.grin-forum.org/t/grin-improvement-proposal-1-put-later-phase-outs-on-hold-and-rephrase-primary-pow-commitment) 
1. Security
   1. Audit status
   1. [Create Grin Bug Bounty proposal](https://github.com/mimblewimble/grin-pm/issues/149)
   1. Add a third contact to `SECURITY.md`, proposed: @hashmap  
1. [Governance iteration](https://www.grin-forum.org/t/proposal-grin-governance-iteration/5191)
1. Funding status
   1. [Budget status](https://github.com/mimblewimble/grin-pm/issues/130)
1. Other questions

**Comment by tromp** [comment]
Need to decide on https://www.grin-forum.org/t/grin-improvement-proposal-1-put-later-phase-outs-on-hold-and-rephrase-primary-pow-commitment

**Comment by lehnberg** [comment]
Agenda updated

**Comment by chisa0a** [comment]
I would like to suggest adding an item for [bug bounty](https://github.com/mimblewimble/grin-pm/issues/149) discussion.

**Comment by lehnberg** [comment]
Updated, also added a proposal to add @hashmap as point of contact for `SECURITY.md`.

**Comment by lehnberg** [comment]
Edited the agenda point order.
