### ISSUE TITLE
Agenda: Governance Nov 20, 2018

### ISSUE THREAD

**Issue by lehnberg** [mimblewimble/grin-pm#17]
Solicit suggestions for agenda items for the Governance meeting to be held on Tuesday Nov 20 @ 15:00 UTC in Gitter main lobby. Please comment to provide topics or suggestions.

# Proposed agenda
1. Agenda review
1. Action point follow ups from [previous meeting](https://github.com/mimblewimble/grin-pm/blob/master/notes/20181106-meeting-governance.md)
   1. @yeastplume to check with accountants re audit
   1. @lehnberg to put together a first draft of security brief.
   1. Council members to complete risk assessment
1. PoW
1. [Security reviews / audits](https://github.com/mimblewimble/grin/issues/1609)
   1. End the security audit soon funding campaign sometime between now and end of the month.
   1. See what subset we can get audited with what we have, see https://github.com/mimblewimble/grin-pm/issues/20 for a reduced scope proposal. Do not require the audit to be completed before mainnet, it can go in parallel.
1. Mainnet planning
   1. Proposed release target: Jan 15th 2019
   1. Genesis block release process
1. Working with exchanges
1. Dealing with conflicts of interests
1. [Mission statement: Update](https://www.grin-forum.org/t/help-us-write-grins-mission-statement/1114/)
1. Website content
1. [Website design](https://www.grin-forum.org/t/help-me-design-and-add-content-to-our-site/1035/)
1. Risk mgmt brainstorm
1. Other questions

**Comment by ignopeverell** [comment]
Genesis block release process.

**Comment by quentinlesceller** [comment]
Define a clear policy regarding communication with exchanges.

**Comment by lehnberg** [comment]
Updated and tidied up the agenda - also re-ordered some stuff. PoW feels less controversial these days so we might as well deal with it earlier on as it's important.

**Comment by ignopeverell** [comment]
Looks like it's going to be a long one. I'd like to discuss the following release plan as well:

1. End the security audit soon funding campaign sometime between now and end of the month.
2. See what subset we can get audited with what we have, see #20 for a reduced scope proposal. Do not require the audit to be completed before mainnet, it can go in parallel.
2. Plan for a mainnet release on Jan 15th 2019.

**Comment by lehnberg** [comment]
Agenda updated and tidied up accordingly.

**Comment by lehnberg** [comment]
Closed via #21
