### ISSUE TITLE
Resources for new contributors?

### ISSUE THREAD

**Issue by casey** [mimblewimble/grin-pm#2]
I was thinking that it might be a good idea to collect resources for new contributors to grin in one place, might this repo be a good place for that? The website might be another place to do it.

Some ideas for things that would help people jump into the codebase:
- Links to issues tagged [help wanted](https://github.com/mimblewimble/grin/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22)
- Links to issues tagged [good first issue](https://github.com/mimblewimble/grin/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22+label%3A%22good+first+issue%22)
- List of larger projects or features which are generally agreed on as being desirable, but nobody is necessarily working on. I'm thinking of betterhash and a DHT, but there are almost certainly more. Currently, these kinds of things are usually discussed on the mailing list or in chat, making them hard for a potential contributor to discover.

**Comment by lehnberg** [comment]
Good thinking @casey! 

In terms of location, I think the suggestion itself belonged as an issue here in `/grin-pm` (just like you did basically) as it allows us to track it and close it once done. Thanks for raising it! 

For the actual resource, I would suggest we do it on the wiki, to allow community members to be able to update it freely. Makes sense?

**Comment by casey** [comment]
Sounds good! Should I start a page in github.com/mimblewimble/docs/wiki?

**Comment by lehnberg** [comment]
Go for it! You might also consider to just add and improve on this one: https://github.com/mimblewimble/docs/wiki/Hacking-and-contributing

**Comment by casey** [comment]
Just added a simple section at the end of the Hacking and Contributing section.
