### ISSUE TITLE
Minimal scope for security audit

### ISSUE THREAD

**Issue by ignopeverell** [mimblewimble/grin-pm#20]
This is a first pass at detailing what could encompass a minimum but still reasonable audit scope. This would focus on cryptographic and consensus-critical code.

* ~~Diff between [our version of rust-secp256k1](https://github.com/mimblewimble/rust-secp256k1-zkp) and [upstream](https://github.com/rust-bitcoin/rust-secp256k1).~~
* ~~Diff between [our version of libsecp256k1](https://github.com/mimblewimble/secp256k1-zkp) and [upstream](https://github.com/ElementsProject/secp256k1-zkp).~~
* The Grin [core crate](https://github.com/mimblewimble/grin/tree/master/core)
* The Grin [keychain crate](https://github.com/mimblewimble/grin/tree/master/keychain)
* The Grin [chain crate](https://github.com/mimblewimble/grin/tree/master/chain)

If it helps I can produce the diffs for the first 2 points and count the LoC, but overall this shouldn't be that much code.

/cc @Catheryne

Edit: since the 2 first items have been reviewed by JP Aumasson, a full audit on them has become far less pressing. The last 3 items remain important however.

**Comment by Catheryne** [comment]
I'll contact all the audit companies with this reduced scope and get bids.

**Comment by lehnberg** [comment]
@ignopeverell can you add wallet crate to this? IIRC we said that would also be included.

**Comment by lehnberg** [comment]
fixed, and audit is underway.
