### ISSUE TITLE
Agenda: Governance Feb 25 2020

### ISSUE THREAD

**Issue by lehnberg** [mimblewimble/grin-pm#254]
Solicit suggestions for agenda items for the Governance meeting to be held on Tuesday Feb 25 @ 15:00 [UTC](http://www.timebie.com/std/utc.php) in [Keybase main lobby](http://keybase.io/team/grincoin). Please comment to provide topics or suggestions.

# Proposed agenda
1. Agenda review
1. Action point follow ups from previous meeting
   * [ ] grin.mw domain access: shards are distributed?
1. Proposal by @bladedoyle:
   > increase the salary by 10% for dev team members who have not had any increase recently
1. [Funding request](https://forum.grin.mw/t/request-for-funding-jaspervdm-march-may-2020/7074), @jaspervdm 
1. [How are repos added to the Mimblewimble org](https://github.com/mimblewimble/grin-pm/issues/253)
1. RFC & sub-teams update
1. Other questions

**Comment by bladedoyle** [comment]
Salary increase for grin developers.  
I suggest we increase the salary by 10% for dev team members who have not had any increase recently
