### ISSUE TITLE
Agenda: Governance, May 05 2020

### ISSUE THREAD

**Issue by lehnberg** [mimblewimble/grin-pm#285]
Solicit suggestions for agenda items for the Governance meeting to be held on Tuesday May 05 @ 15:00 [UTC](http://www.timebie.com/std/utc.php) in [Keybase main lobby](http://keybase.io/team/grincoin). Please comment to provide topics or suggestions.

# Proposed agenda
1. Agenda review
1. Action point follow ups from previous meeting
   * [ ] new keybase structure?
1. [GUI wallets](https://forum.grin.mw/t/the-official-grin-gui-wallet/7209): action plan & timeframes
1. RFC & sub-teams update
1. Other questions

**Comment by yeastplume** [comment]
If there is a dearth of topics to discuss, I wouldn't mind some discussion on https://forum.grin.mw/t/the-official-grin-gui-wallet/7209, and perhaps come up with an action plan and timeframes
