### ISSUE TITLE
Agenda: Development, Dec 27

### ISSUE THREAD

**Issue by lehnberg** [mimblewimble/grin-pm#29]
Solicit suggestions for agenda items for the Development meeting to be held on Thursday Dec 27 @ 15:00 [UTC](http://www.timebie.com/std/utc.php) in [Grin/Dev Gitter](
https://gitter.im/grin_community/dev). Please comment to provide topics or suggestions. 

# Proposed agenda
1. Igno's Retrospective
1. Agenda review
1. Action point follow ups from previous meetings
1. PoW general item
1. Results from libsecp audit
   1. Related: https://github.com/mimblewimble/grin/issues/2218
1. [Mainnet planning](https://github.com/mimblewimble/grin/milestone/4)
   1. Betanet status
   1. Genesis status
1. Post-mainnet release planning.
   1. How do we plan releases?
   1. How do we decide what features go into each release? 
1. Other questions

**Comment by yeastplume** [comment]
I do think we need to start thinking about post-mainnet release planning. Specifically, how we plan releases and how we decide what features go into each release. This topic probably crosses over with governance

**Comment by lehnberg** [comment]
Agenda updated, added this point. I think it makes sense to have it be development driven.

**Comment by ignopeverell** [comment]
We should also discuss current results from the code review of libsecp and its use in Grin.

**Comment by lehnberg** [comment]
Makes sense, updated
