### ISSUE TITLE
Introduce a decision log

### ISSUE THREAD

**Issue by lehnberg** [mimblewimble/grin-pm#30]
In a [recent developer meeting](
https://github.com/mimblewimble/grin-pm/blob/master/notes/20181211-meeting-development.md#3-action-point-follow-up) a suggestion was made for "a place to store previous made community decisions and up to date policies". Potential areas where this could be kept include the main wiki, `grin-pm/`, `grin/doc/`, and on `site/`. Not all decisions and documentation are relevant to each of these areas, and I'm not sure ist one ideal location for all types of policies and documentation. 

Instead, I propose that we create a "community decision log", that chronologically tracks decisions (and revisions alike) with a time stamp, where the decisions were made, and a reference to any specific policy, note that accompanies it. This way, we have a single central place for an overview of all the decisions, and when they were changed, while we keep each policy / doc in the location it should best be in. The log itself resides on `/grin-pm` and appends are made through PRs.

**Comment by lehnberg** [comment]
@kargakis @ignopeverell makes sense?

**Comment by kargakis** [comment]
grin-pm sounds good to me. My only suggestion re the site was that wherever we store this info, it should be discoverable from the site.

**Comment by ignopeverell** [comment]
Makes sense to me as long as it doesn't become a pain to maintain.

**Comment by dewdeded** [comment]
Very good one, was always missed in so many projects before.

**Comment by lehnberg** [comment]
Fixed by https://github.com/mimblewimble/grin-pm/pull/47
