### ISSUE TITLE
Update Code of Conduct

### ISSUE THREAD

**Issue by lehnberg** [mimblewimble/grin-pm#309]
A recent [forum thread](https://forum.grin.mw/t/grin-code-of-conduct/7477) led me to review [mimblewimble/grin/CODE_OF_CONDUCT.md](https://github.com/mimblewimble/grin/blob/master/CODE_OF_CONDUCT.md) and consider feedback raised by `@Kurt` in thread. The code has not materially changed since 2017, and I think there is room to improve. Specifically, these are a some (unpolished) thoughts: 

* [x] Not sure who has access to grinmods@googlegroups.com these days, needs investigating.

* [x] Currently, it's called "Grin Code of Conduct". This is ambiguous as it's the name of the repository it is located in and covers, but also a wider project "Grin" which can have multiple communities, GitHub organizations, and codes of conduct. We should try to avoid this confusion if we can, potentially by only calling it "Code of Conduct".

* [x] Since the code of conduct covers more than just the `mimblewimble/grin` repo, (also `/grin-wallet/`, `/site`, keybase, etc), we might consider moving it under the grin.mw website instead and pointing to it from various repos and locations (including `/grin-pm`). 

* [x] Contains references to Gitter and IRC, but not keybase, or forum. It might make sense to not actually name specific tools or communities explicitly as that may change in the future. Instead, scope should probably any place where contributors to the `/mimblewimble/` org are and are acting as contributors of `/mimblewimble` or something like that. I.e. it's less about which chat room you are in, and more about whether you are presenting yourself as a `/mimblewimble` contributor. If you do, then there are some expectations about how you are meant to be conducting yourself, and if you violate them, you may not be welcome as a contributor any more. This needs more thought behind it and better wording.

* [ ] Not sure actual detailed moderation actions and steps should be in the CoC, and might be better left to the moderators themselves to define.

* [x] The contributor covenant it is based on is v1.3, and [has since been updated to v2.0](https://www.contributor-covenant.org/version/2/0/code_of_conduct/). It makes sense to review and refresh to remain up to date.

* [ ] Overall if we can make the text more condensed and focused, it might become easier to read and more powerful.

**Comment by Paouky** [comment]
I gave it a try but sitting for an hour got me practically nowhere, I'm no good at this.
But here a few of my suggestions to whoever decides to tackle this in the future:

1. Switch the first paragraph with this one, taken from the Go CoC.

> Online communities include people from many different backgrounds. The Grin contributors are committed to providing a friendly, safe and welcoming environment for all, regardless of gender identity and expression, sexual orientation, disabilities, neurodiversity, physical appearance, body size, ethnicity, nationality, race, age, religion, or similar personal characteristics. 

2. Remove the word 'Grin' from the title, as lehnberg suggested.

3. Cut the whole thing in half. It's supposed to capture the spirit, not the detailed definitions of everything. More like a constitution.

4. Don't make it about people's rights. Make it about people's duties and obligations.
Take the first amendment as an example: 

> Congress shall make no law respecting an establishment of religion, or prohibiting the free exercise thereof; or abridging the freedom of speech, or of the press; or the right of the people peaceably to assemble, and to petition the government for a redress of grievances.

No where is it mentioned that a person has a right to free speech. It is said that the congress (representing the people) have an OBLIGATION to not prohibit nor interfere with other people's freedom of expression.

**Comment by lehnberg** [comment]
Fixed by [mimblewimble/site#222](https://github.com/mimblewimble/site/pull/222)
