### ISSUE TITLE
Agenda: Development (+ Governance), Dec 22 2020

### ISSUE THREAD

**Issue by lehnberg** [mimblewimble/grin-pm#376]
Solicit suggestions for agenda items for the Development meeting to be held on Tuesday Dec 22 @ 15:00 [UTC](http://www.timebie.com/std/utc.php) in [grincoin#dev channel on Keybase](
https://keybase.io/team/grincoin). Please comment to provide topics or suggestions. 

# Proposed agenda
1. Antiochp update
1. Agenda review
1. Action point follow ups from previous meetings
   * [ ] Slatepack comms
1. Funding request: [David Tavarez Q1 2021](https://forum.grin.mw/t/request-for-funding-davidtavarez-q1-jan-mar-2021/8073/8)
1. v5.0.0 status:
   * Planning issue: https://github.com/mimblewimble/grin-pm/issues/287
   * Project board: https://github.com/orgs/mimblewimble/projects/1 
1. API listening on 0.0.0.0
1. Aliases for [wallet transaction rounds](https://forum.grin.mw/t/transaction-round-naming-challenge/7886/48)
1. Other questions

**Comment by antiochp** [comment]
In terms of 5.0.0 final release - is there any reason we want to wait until Jan 5 to release it?
There is no last minute AR changes that we need to wait for.

`5.0.0-rc.1` is exactly what we will release, barring any last minute changes.
