### ISSUE TITLE
2021 Q1 financial transparency report is missing

### ISSUE THREAD

**Issue by l33d4n** [mimblewimble/grin-pm#421]
The general fund page has not been updated for months:
https://github.com/mimblewimble/site/issues/255

**Comment by MCM-Mike** [comment]
not sure, is this related to it as well: https://github.com/mimblewimble/grin-pm/issues/414 ?

**Comment by l33d4n** [comment]
You're right, it's related but these are different files so I guess these are different tasks.

The spending log: https://github.com/mimblewimble/grin-pm/blob/master/financials/spending_log.csv
The transparency reports: https://github.com/mimblewimble/grin-pm/tree/master/financials/reports

**Comment by quentinlesceller** [comment]
Reminder that anyone can take this task and do it.

**Comment by l33d4n** [comment]
@quentinlesceller This is one of the tasks in-scope that **approved and funded** by the council in: 
[Request for Funding, @lehnberg: Q1 (Jan-Mar) 2021](https://forum.grin.mw/t/request-for-funding-lehnberg-q1-jan-mar-2021/8040)

> ### Specific tasks in-scope
> Financials / book keeping
> Keep grin-pm/financials/ 3 up do date.
> Publish quarterly transparency reports
>
> ### Funding request
> GBP £2,500/month
> 3 months, Q1 2021, jan-mar

**Comment by l33d4n** [comment]
Probably nothing is going to happen. Closed.
