### ISSUE TITLE
Add Presentation Template

### ISSUE THREAD

**Issue by RyanHu1208** [mimblewimble/grin-pm#43]
hi @lehnberg 

this is from noahyeh at gitter
please take a look

https://github.com/RyanHu1208/grin-pm/tree/master/presentations/templates

thank you

**Comment by lehnberg** [comment]
@RyanHu1208 looks good, thank you very much!

Suggestions:
- rename `GrinDeckTemplates.md` to `README.md`
- add 'description' column with a brief description of your template

Makes sense? :)

**Comment by kargakis** [comment]
@lehnberg there is a `README.md` file in grin-pm already. Maybe use something like `PRESENTATIONS.md` and link to it from `README.md`?

**Comment by kargakis** [comment]
> @lehnberg there is a `README.md` file in grin-pm already. Maybe use something like `PRESENTATIONS.md` and link to it from `README.md`?

OK, seems like the presentations table is already part of README.md

https://github.com/mimblewimble/grin-pm#presentations

**Comment by lehnberg** [comment]
I'm merging. Improving is infinite, something is better than nothing, no need to overthink it, we can always make it better later!

**Comment by lehnberg** [comment]
Oh lol... didn't realise this was an issue. @RyanHu1208 this looks good - can you open a pull request merging your proposed changes?
